package parser.ll1.grammar;

public enum NonTerminal implements Symbol {
    MODULE,
    PARAM_LIST, PARAM_LIST_REST, PARAM,
    ARG_LIST,   ARG_LIST_REST,   ARG,
    SEPAR,
    INSTANCE_LIST, INSTANCE_LIST_REST, INSTANCE,
    ASSIGN_OR_TRI, TRI_STATE_TAIL,
    MEMORY_POINT, MEM_TAIL, SET_RESET, OPT_COMMA, OPT_SEMI, OPT_SEMI_OR_COMMA,
    MODULE_INSTANCE,
    MAP, MAP_VALUE_LIST, MAP_VALUE,
    FSM, FSM_KEYWORD, FSM_HEADER, FSM_RULE_LIST, FSM_RULE, FSM_RULE_REST, FSM_RULE_LEFT,
    STATE_NAME_LIST, STATE_NAME_LIST_REST,
    SUM_OF_TERMS_COMPOUND, SUM_OF_TERMS_COMPOUND_REST,
    SUM_OF_TERMS, SUM_OF_TERMS_REST,
    TERM, TERM_REST, FACTOR,
    SIGNAL_COMPOUND, SIGNAL_COMPOUND_REST,
    SIGNAL, SIGNAL_TAIL, SIGNAL_AFTER_INT,
    SIGNAL_OR_LITERAL;

    @Override public boolean isNonTerminal() { return true; }
}
